project/models/Actor.py
from project import db

class Actor(db.Model):
    __tablename__ = 'actor'
    show_id = db.Column(db.String(50), db.ForeignKey('netflix.show_id'))
    actor_name = db.Column(db.String(1000))
    __mapper_args__ = {
        "primary_key": [show_id,actor_name]
    }

project/models/Country.py
from project import db

class Country(db.Model):
    __tablename__ = 'country'
    show_id = db.Column(db.String(50), db.ForeignKey('netflix.show_id'))
    country_name = db.Column(db.String(100))
    __mapper_args__ = {
        "primary_key": [show_id,country_name]
    }

project/models/Director.py
from project import db

class Director(db.Model):
    __tablename__ = 'director'
    show_id = db.Column(db.String(50), db.ForeignKey('netflix.show_id'))
    director_name = db.Column(db.String(100))
    __mapper_args__ = {
        "primary_key": [show_id,director_name]
    }

project/models/Genre.py
from project import db

class Genre(db.Model):
    __tablename__ = 'genres'
    genre_id = db.Column(db.Integer,primary_key=True)
    genre = db.Column(db.String(255))
    

project/models/Netflix.py
from project import db

class Netflix(db.Model):
    __tablename__ = 'netflix'
    show_id = db.Column(db.String(50),primary_key=True)
    show_type = db.Column(db.String(20))
    title = db.Column(db.String(500))
    date_added = db.Column(db.Date)
    release_year = db.Column(db.Integer)
    rating = db.Column(db.String(50))
    duration = db.Column(db.String(50))
    description = db.Column(db.String(1000))

project/models/ShowGenre.py
from project import db

class ShowGenre(db.Model):
    __tablename__ = 'show_genre'
    show_id = db.Column(db.String(50), db.ForeignKey('netflix.show_id'))
    genre_id = db.Column(db.Integer,db.ForeignKey('genres.genre_id'))
    __mapper_args__ = {
        "primary_key": [show_id,genre_id]
    }

project/models/User.py
from flask_login import UserMixin
from project import db


class User(UserMixin,db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True) 
    password = db.Column(db.String(255))
    first_name = db.Column(db.String(255))
    last_name = db.Column(db.String(255))
    email = db.Column(db.String(255))

project/models/__init__.py
from project.models.User import User
from project.models.Actor import Actor
from project.models.Country import Country
from project.models.Director import Director
from project.models.Genre import Genre
from project.models.Netflix import Netflix
from project.models.ShowGenre import ShowGenre

project/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

# init SQLAlchemy so we can use it later in our models

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_message = 'Please login to continue'
login_manager.login_view = 'user.login'
login_manager.login_message_category = 'info'

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'root'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://postgres:Jonsnow1310*@localhost:5432/ADT'
    db.init_app(app)
    login_manager.init_app(app)
    login_manager.session_protection = "strong"

    from project.models.User import User
    from project.main.routes import main


    @login_manager.user_loader
    def load_user(user_id):
        # since the user_id is just the primary key of our user table, use it in the query for the user
        return User.query.get(int(user_id))

    # blueprint for auth routes in our app
    from project.routes import routes as routes_blueprint
    app.register_blueprint(routes_blueprint)
    from project.models.User import User
    # blueprint for non-auth parts of app
    app.register_blueprint(main)
        
    from project.netflix.netflixUtility import netflixUtility as netflixUtility_blueprint
    app.register_blueprint(netflixUtility_blueprint)


    #from project import db, create_app, models
    with app.app_context():
        db.create_all()
        db.session.commit()

    return app

project/main.py
from flask import Blueprint,render_template

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

project/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('main/index.html')

project/routes.py
from flask import Blueprint,render_template,redirect, url_for,flash, request
from werkzeug.security import generate_password_hash
from project.models import User
from project import db
from flask_login import login_user, login_required, logout_user
from threading import Thread


routes = Blueprint('routes', __name__)


@routes.route('/login')
def login():
    return render_template('login.html')

@routes.route('/signup')
def signup():
    return render_template('signup.html')

@routes.route('/signup', methods=['GET','POST'])
def signup_post():
    if "post":
        email = request.form.get('email')
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        password = request.form.get('password')
        confirm_password = request.form.get('password')
        user = User.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database

        if password!=confirm_password:
            flash('Password does not match')
            return redirect(url_for('routes.signup'))
        
        if user: # if a user is found, we want to redirect back to signup page so user can try again
            flash('Email address already exists')
            return redirect(url_for('routes.signup'))
 
        # create a new user with the form data. Hash the password so the plaintext version isn't saved.
        new_user = User(email=email, first_name=firstname,last_name=lastname, password=generate_password_hash(password, method='sha256'))

        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('routes.login'))
    else:
        return render_template('signup.html')

 
@routes.route('/login', methods=['POST'])
def login_post():
    # login code goes here
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    print('SE project')
    user = User.query.filter_by(email=email).first()
    login_user(user, remember=remember)
    return redirect(url_for('netflixUtility.viewNetflix'))   

@routes.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

project/templates/error_handler/error_404.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7 col-sm-10">
                <img src="{{ url_for('static', filename='error_logo/error_404.svg') }}"
                    alt="error_404" class="img-fluid d-block mx-auto">
                <h1 class="mt-3">
                    Sorry for the inconvinience!
                </h1>
                <div class="text-center">
                    <a class="btn btn-primary" href="{{ url_for('main.index') }}">Click Here</a>
                </div>
            </div>
        </div>

    </div>
{% endblock content %}

project/templates/error_handler/error_429.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="container-fluid ">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7 col-sm-10">
                <h1 class="mt-3">
                    Sorry for the inconvinience!
                </h1>
                <img src="{{ url_for('static', filename='error_logo/error_429.svg') }}"
                    alt="error_429" class="img-fluid d-block mx-auto">
                <div class="text-center">
                    <a class="btn btn-primary" href="{{ url_for('main.index') }}">Click Here</a>
                </div>
            </div>
        </div>

    </div>
{% endblock content %}

project/templates/error_handler/error_500.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="container-fluid mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7 col-sm-10">
                <img src="{{ url_for('static', filename='error_logo/error_500.svg') }}"
                    alt="error_500" class="img-fluid d-block mx-auto">
                <h1 class="mt-3">
                    Sorry for the inconvinience!
                </h1>
                <div class="text-center">
                    <a class="btn btn-primary" href="{{ url_for('main.index') }}">Click Here</a>
                </div>
            </div>
        </div>

    </div>
{% endblock content %}

project/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Pages</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap');
*{
    margin: 0%;
    padding: 0%;
    box-sizing: border-box;
    font-family:'Poppins',sans-serif;
}
body{
    overflow: hidden;
}
section{
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100em;
    background: linear-gradient(to bottom,#f1f4f9,#dff1ff);
}
section .color{
    position: absolute;
    filter: blur(150px);
}
section .color:nth-child(1)
{
    top: -350px;
    width: 900px;
    height: 600px;
    background: red;
}
section .color:nth-child(2)
{
    bottom: -150px;
    left: 100px;
    width: 500px;
    height: 500px;
    background: black;
}
section .color:nth-child(3)
{
    bottom: 50px;
    right: 100px;
    width: 700px;
    height: 400px;
    background: white;
}
.box{
    position:relative;
    top: -470px;
}
.box .square{
    position: absolute;
    backdrop-filter: blur(5px);
    box-shadow: 0 25px 45px rgba(0,0,0,0.1);
    border: 1px solid red;
    border-right: 1px solid white;
    border-bottom: 1px solid black;
    background: black;
    border-radius: 10px;
    animation: animate 10s linear infinite;
    animation-delay: calc(-1s * var(--i));
}
@keyframes animate {
    0%,100%{
        transform: translateY(-40px);
    }
    50%{
        transform: translateY(40px);
    }
}
.box .square:nth-child(1){
    top: -50px;
    right: -60px;
    width: 100px;
    height: 100px;
    
}
.box .square:nth-child(2){
    top: 150px;
    left: -100px;
    width: 120px;
    height: 120px;
    z-index: 2;
}
.box .square:nth-child(3){
    bottom: 50px;
    right: -60px;
    width: 80px;
    height: 80px;
    z-index: 2;
}
.box .square:nth-child(4){
    bottom: -80px;
    left: 100px;
    width: 50px;
    height: 50px;
}
.box .square:nth-child(5){
    top: -80px;
    left: 140px;
    width: 60px;
    height: 60px;
}
.container{
    position: relative;
    width: 400px;
    min-height: 400px;
    background:rgba(255,255,255,0.1);
    border-radius: 10px;
    justify-content: center;
    display: flex;
    align-items: center;
    backdrop-filter: blur(5px);
    box-shadow: 0 25px 45px rgba(0,0,0,0.1);
    border: 1px solid rgba(255,255,255,0.5);
    border-right: 1px solid rgba(255,255,255,0.2);
    border-bottom: 1px solid rgba(255,255,255,0.2);
}
.form{
    position: relative;
    width: 100%;
    height: 100%;
    padding: 40px;

}
.form h2{
    position: relative;
    color: rgb(32, 31, 31);
    font-size: 24px;
    font-weight: 600;
    letter-spacing: 1px;
    margin-bottom: 40px;
}
.form h2::before{
    content: '';
    position: absolute;
    left: 0;
    bottom: -10px;
    width: 80px;
    height: 4px;
    background:white;
}
.form .inputBox{
    width: 100%;
    margin-top: 20px;

}
.form .inputBox input{
    width: 100%;
    background: rgba(255,255,255,0.2);
    border: none;
    outline: none;
    padding: 10px 20px;
    border-radius: 35px;
    border: 1px solid rgba(255,255,255,0.5);
    border-right: 1px solid rgba(255,255,255,0.2);
    border-bottom: 1px solid rgba(255,255,255,0.2);
    font-size: 16px;
    letter-spacing: 1px;
    color: rgb(52, 49, 49);
    box-sizing: 0 5px 15px rgba(0,0,0,0.05);
}
.form .inputBox input::placeholder{
    color: rgb(31, 30, 30);
}
.form .inputBox input[type="submit"]{
    background: white;
    color: #666;
    max-width: 100px;
    cursor: pointer;
    margin-bottom: 20px;
    font-weight: 600;
}
.forget{
    margin-top: 5px;
    color: rgb(22, 21, 21);
}
.forget a{
    color: rgb(16, 16, 16);
    font-weight: 600;
    text-decoration: none;
}
#menuToggle
{
  display: block;
  position: relative;
  top: 50px;
  left: 50px;
  
  z-index: 1;
  
  -webkit-user-select: none;
  user-select: none;
}

#menuToggle a
{
  text-decoration: none;
  color: #232323;
  
  transition: color 0.3s ease;
}

#menuToggle a:hover
{
  color: tomato;
}


#menuToggle input
    {
    display: block;
    width: 40px;
    height: 32px;
    position: absolute;
    top: -7px;
    left: -5px;
    
    cursor: pointer;
    
    opacity: 0; /* hide this */
    z-index: 2; /* and place it over the hamburger */
    
    -webkit-touch-callout: none;
    }

    /*
    * Just a quick hamburger
    */
    #menuToggle span
    {
    display: block;
    width: 33px;
    height: 4px;
    margin-bottom: 5px;
    position: relative;
    
    background: #e76b6b;
    border-radius: 3px;
    
    z-index: 1;
    
    transform-origin: 4px 0px;
    
    transition: transform 0.5s cubic-bezier(0.77,0.2,0.05,1.0), background 0.5s cubic-bezier(0.77,0.2,0.05,1.0),
                opacity 0.55s ease;
    }

    #menuToggle span:first-child
    {
    transform-origin: 0% 0%;
    }

    #menuToggle span:nth-last-child(2)
    {
    transform-origin: 0% 100%;
    }

    /* 
    * Transform all the slices of hamburger
    * into a crossmark.
    */
    #menuToggle input:checked ~ span
    {
    opacity: 1;
    transform: rotate(45deg) translate(-2px, -1px);
    background: #232323;
    }

    /*
    * But let's hide the middle one.
    */
    #menuToggle input:checked ~ span:nth-last-child(3)
    {
    opacity: 0;
    transform: rotate(0deg) scale(0.2, 0.2);
    }

    /*
    * Ohyeah and the last one should go the other direction
    */
    #menuToggle input:checked ~ span:nth-last-child(2)
    {
    transform: rotate(-45deg) translate(0, -1px);
    }

    /*
    * Make this absolute positioned
    * at the top left of the screen
    */
    #menu
    {
    position: absolute;
    width: 300px;
    margin: -100px 0 0 -50px;
    padding: 50px;
    padding-top: 125px;
    
    background: #d9e2dd92;
    list-style-type: none;
    -webkit-font-smoothing: antialiased;
    /* to stop flickering of text in safari */
    
    transform-origin: 0% 0%;
    transform: translate(-100%, 0);
    
    transition: transform 0.5s cubic-bezier(0.77,0.2,0.05,1.0);
    }

    #menu li
    {
    padding: 10px 0;
    font-size: 22px;
    }

    /*
    * And let's slide it in from the left
    */
    #menuToggle input:checked ~ ul
    {
    transform: none;
    }
    </style>
    
</head>

<body>
    <nav role="navigation">
        <div id="menuToggle">
          <input type="checkbox" />     

          <span></span>
          <span></span>
          <span></span>
          
          <ul id="menu">
            <a href="{{ url_for('main.index') }}"><li>Home</li></a>
          </ul>
        </div>
      </nav>

    <section>
        <div class="color">
         </div>
        <div class="color">
         </div>
        <div class="color">
         </div>  
        <div class="box">
           
            <div class="container">
                <div class="form">
                    <h2>Login Form</h2>
                    <form method="POST" action="/login">
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            <div class="notification is-danger">
                                {{ messages[0] }}
                            </div>
                        {% endif %}
                        {% endwith %}
                        <form method="POST" action="/login">
                            <div class="inputBox">
                                <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">

                            </div>
                            <div class="inputBox">
                                <input class="input is-large" type="password" name="password" placeholder="Your Password">
                            </div>
                            <div class="inputBox">
                                <input type="submit" value="Login">
                            </div>
                            <p class="forget">Don't have an account ?<a href="{{ url_for('routes.signup') }}"> Sign up</a></p>
                    </form>
                </div>
            </div>
        </div>
    </section>
    
</body>
</html>

project/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FLix IQ</title>

</head>
<style>
    :root{
        --green:#FF0000;
        --black:#444;
        --light-color:#777;
        --box-shadow:.5rem .5rem 0 rgba(22, 160, 133, .2);
        --text-shadow:.4rem .4rem 0 rgba(0, 0, 0, .2);
        --border:.2rem solid var(--green);
    }

    *{
        font-family: 'Poppins', sans-serif;
        margin:0; padding: 0;
        box-sizing: border-box;
        outline: none; border: none;
        text-transform: capitalize;
        transition: all .2s ease-out;
        text-decoration: none;
    }

    html{
        font-size: 62.5%;
        overflow-x: hidden;
        scroll-padding-top: 7rem;
        scroll-behavior: smooth;
    }

    .header{
        padding:0.8rem 8%;
        position: fixed;
        top:0; left: 0; right: 0;
        z-index: 1000;
        box-shadow: 0 .5rem 1.5rem rgba(0, 0, 0, .1);
        display: flex;
        align-items: center;
        justify-content: space-between;
        background: black;
    }

    

    .header .navbar a{
        font-size: 1.7rem;
        color: white;
        margin-left: 2rem;
    }

    .header .navbar a:hover{
        color: red;
    }


    /* media queries  */
    @media (max-width:991px){

        html{
            font-size: 55%;
        }

        .header{
            padding: 2rem;
        }

        section{
            padding:2rem;
        }

    }

    @media (max-width:768px){

        #menu-btn{
            display: initial;
        }

        .header .navbar{
            position: absolute;
            top:115%; right: 2rem;
            border-radius: .5rem;
            box-shadow: var(--box-shadow);
            width: 30rem;
            border: var(--border);
            background: black;
            transform: scale(0);
            opacity: 0;
            transform-origin: top right;
            transition: none;
        }

        .header .navbar.active{
            transform: scale(1);
            opacity: 1;
            transition: .2s ease-out;
        }

        .header .navbar a{
            font-size: 2rem;
            display: block;
            margin:2.5rem;
        }

    }

    @media (max-width:450px){

        html{
            font-size: 50%;
        }

    }
</style>


<body>
   <div class="header"> 
    <section class="hero is-primary is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <div class="logo">
                                <img src="static/images/flix_iq_logo.png" alt="" style="  height: 20%; max-height: 70px;">
                            </div>
                        
                            {% if (current_user.is_authenticated) %}
                            <a href="{{ url_for('netflixUtility.viewNetflix') }}" class="navbar-item">
                                Home
                            </a>
                            {% endif %}
                          
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for('routes.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('routes.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('routes.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="hero-body" style="align-items:normal;">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>



</html>

project/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flix IQ</title>
    

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap');

    :root{
        --green:#FF0000;
        --black:#444;
        --light-color:#777;
        --box-shadow:.5rem .5rem 0 rgba(22, 160, 133, .2);
        --text-shadow:.4rem .4rem 0 rgba(0, 0, 0, .2);
        --border:.2rem solid var(--green);
    }

    *{
        font-family: 'Poppins', sans-serif;
        margin:0; padding: 0;
        box-sizing: border-box;
        outline: none; border: none;
        text-transform: capitalize;
        transition: all .2s ease-out;
        text-decoration: none;
    }

    html{
        font-size: 62.5%;
        overflow-x: hidden;
        scroll-padding-top: 7rem;
        scroll-behavior: smooth;
    }

    section{
        padding:2rem 9%;
    }

    section:nth-child(even){
        background: #f5f5f5;
    }

    .heading{
        text-align: center;
        padding-bottom: 2rem;
        text-shadow: var(--text-shadow);
        text-transform: uppercase;
        color:var(--black);
        font-size: 5rem;
        letter-spacing: .4rem;
    }

    .heading span{
        text-transform: uppercase;
        color:var(--green);
    }

    .btn{
        display: inline-block;
        margin-top: 1rem;
        padding: .5rem;
        padding-left: 1rem;
        border:var(--border);
        border-radius: .5rem;
        box-shadow: var(--box-shadow);
        color:var(--green);
        cursor: pointer;
        font-size: 1.7rem;
        background: #fff;
    }

    .btn span{
        padding:.7rem 1rem;
        border-radius: .5rem;
        background: var(--green);
        color:#fff;
        margin-left: .5rem;
    }

    .btn:hover{
        background: var(--green);
        color:#fff;
    }

    .btn:hover span{
        color: var(--green);
        background:#fff;
        margin-left: 1rem;
    }

    .header{
        padding:0.8rem 8%;
        position: fixed;
        top:0; left: 0; right: 0;
        z-index: 1000;
        box-shadow: 0 .5rem 1.5rem rgba(0, 0, 0, .1);
        display: flex;
        align-items: center;
        justify-content: space-between;
        background: black;
    }

    

    .header .navbar a{
        font-size: 1.7rem;
        color: white;
        margin-left: 2rem;
    }

    .header .navbar a:hover{
        color: red;
    }

    #menu-btn{
        font-size: 2.5rem;
        border-radius: .5rem;
        background: #eee;
        color:var(--green);
        padding: 1rem 1.5rem;
        cursor: pointer;
        display: none;
    }

    .home{
        display: flex;
        align-items: center;
        flex-wrap: wrap;
        gap:1.5rem;
        padding-top: 10rem;
    }

    .home .image{
        flex:1 1 45rem;
    }

    .home .image img{
        width: 100%;
    }

    .home .content{
        flex:1 1 45rem;
        text-align: center;
    }

    .home .content h3{
        font-size: 4.5rem;
        color:var(--black);
        line-height: 1.8;
        text-shadow: var(--text-shadow);
    }

    .home .content p{
        font-size: 1.7rem;
        color:var(--light-color);
        line-height: 1.8;
        padding: 1rem 0;
    }

    /* media queries  */
    @media (max-width:991px){

        html{
            font-size: 55%;
        }

        .header{
            padding: 2rem;
        }

        section{
            padding:2rem;
        }

    }

    @media (max-width:768px){

        #menu-btn{
            display: initial;
        }

        .header .navbar{
            position: absolute;
            top:115%; right: 2rem;
            border-radius: .5rem;
            box-shadow: var(--box-shadow);
            width: 30rem;
            border: var(--border);
            background: black;
            transform: scale(0);
            opacity: 0;
            transform-origin: top right;
            transition: none;
        }

        .header .navbar.active{
            transform: scale(1);
            opacity: 1;
            transition: .2s ease-out;
        }

        .header .navbar a{
            font-size: 2rem;
            display: block;
            margin:2.5rem;
        }

    }

    @media (max-width:450px){

        html{
            font-size: 50%;
        }

    }
        </style>

</head>
<body>
    
<!-- header section starts  -->

<header class="header">

    <div class="logo">
        <img src="static/images/flix_iq_logo.png" alt="" style="  height: 20%; max-height: 70px;">
    </div>

    <nav class="navbar">
      <a href="{{ url_for('main.index') }}" class="navbar-item">
        Home
      </a>
      {% if not current_user.is_authenticated %}
      <a href="{{ url_for('routes.login') }}" class="navbar-item">
          Sign In
      </a>
      <a href="{{ url_for('routes.signup') }}" class="navbar-item">
          Sign Up
      </a>
      {% endif %}
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('routes.logout') }}" class="navbar-item">
          Logout
      </a>
      {% endif %}
    </nav>

    <div id="menu-btn" class="fas fa-bars"></div>

</header>
<section class="home" id="home">

  <div class="image">
      <img src="static/images/movie_index.jpg" alt="" style ="max-height = 70px">
  </div>

  <div class="content">
      <h3>Welcome to FLIX IQ</h3>
      <p>A Clever Guide to Netflix Movies and TV Shows</p>
  </div>

</section>

</body>
</html>